export enum ErrorCode {
  EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
  REGISTRATION_FAILED = 'REGISTRATION_FAILED',
  LOGIN_FAILED = 'LOGIN_FAILED',
  EMAIL_NO_AUTHENTICATED = 'EMAIL_NO_AUTHENTICATED',
  INVALID_LINK_EMAIL_VERIFICATION = 'INVALID_LINK_EMAIL_VERIFICATION',
  INCORRECT_PASSWORD = 'INCORRECT_PASSWORD',
  SERVER_ERROR = 'SERVER_ERROR',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL',
  OTP_INVALID = 'OTP_INVALID',
  MISSING_INPUT = 'MISSING_INPUT_INVALID',
}
